### PR TITLE
Add TGA 2024 background

### PR DESCRIPTION
**Pull request by easymac**
# Pull request template
Use this template for all contributions made for the repository.

Please indicate all that apply with a checkmark. To make a check, convert brackets below to `[x]`.

* [x] **Feature implementation**
* [ ] **Bug fix**
* [ ] **Code change/improvement**
* [ ] **String change (i.e. grammar/spelling error or an addition)**

***

## Describe what your pull request does
Adds TGA 2024 background for TGA 2024 event Wahoo!

## Related issues and extra details
Link to any issues that this PR is related to and include extra info such as pictures, if applicable.

### CODE REVIEW

**Review by MattBSG — CHANGES_REQUESTED** [review]
Text is difficult to read on this in the messages and local time fields, are we able to clean up the coloring or placement to help it sit better?
profile

**Comment by easymac** [comment]
Thoughts on this gradient effect behind the "Messages sent" and "Local time" text?

revision-mockup

**Comment by MattBSG** [comment]
I think that looks a lot better, and is subtle enough that it doesn't break up the overall design

**Comment by easymac** [comment]
Added the gradient effect—let me know if you have any other feedback; I'm happy to make improvements

**Review by MattBSG — APPROVED** [review]
Looks good to me!

**Pull request merged**
