### PR TITLE
GMT Offset -> Local time

### PR DESCRIPTION
**Pull request by mralext20**
# Pull request template
Use this template for all contributions made for the repository.

Please indicate all that apply with a checkmark. To make a check, convert brackets below to `[x]`.

* [x] **Feature implementation**
* [ ] **Bug fix**
* [ ] **Code change/improvement**
* [ ] **String change (i.e. grammar/spelling error or an addition)**

***

## Describe what your pull request does
instead of displaying the GMT offset, this change makes the profile card display the actual time for the target user. 

## Related issues and extra details
Link to any issues that this PR is related to and include extra info such as pictures, if applicable.

### CODE REVIEW

**Comment by mralext20** [comment]
this still need approval from @FlapSnapple

**Comment by mralext20** [comment]
# Before

# After

**Comment by FlapSnapple** [comment]
image
What if we slapped the timezone in parenthesis after the local time? I'm good with it if we can do that. I don't want to lose information.

**Review by MattBSG — CHANGES_REQUESTED** [review]
Follow new format

**Comment by 7bitlyrus** [comment]
> 
> 
> image
> What if we slapped the timezone in parenthesis after the local time? I'm good with it if we can do that. I don't want to lose information.

One issue with this: not all timezone have a :00 minute offset. Namely, areas such as some Canadian providences, across Australia, the middle east, and some islands.

**Comment by 7bitlyrus** [comment]
New layout previews:
image
image

**Review by MattBSG — APPROVED** [review]

**Pull request merged**
